package com.esiag.server;


/**
* InterfaceIDL/ImprimanteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Imprimante.idl
* mercredi 6 octobre 2010 13 h 35 CEST
*/

public interface ImprimanteOperations 
{
  void getInfo (org.omg.CORBA.StringHolder imprimante, org.omg.CORBA.StringHolder serveur, org.omg.CORBA.StringHolder hostname, org.omg.CORBA.ShortHolder tacheEnCours);
  short printDocument (String nomFichier, org.omg.CORBA.IntHolder nbOctets) throws TacheRefusee;
} // interface ImprimanteOperations
