package com.esiag.server;

/**
* InterfaceIDL/TacheRefuseeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Imprimante.idl
* mercredi 6 octobre 2010 13 h 35 CEST
*/

public final class TacheRefuseeHolder implements org.omg.CORBA.portable.Streamable
{
  public TacheRefusee value = null;

  public TacheRefuseeHolder ()
  {
  }

  public TacheRefuseeHolder (TacheRefusee initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TacheRefuseeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TacheRefuseeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TacheRefuseeHelper.type ();
  }

}
