package CosEvent;

/**
* CosEvent/CanalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public final class CanalHolder implements org.omg.CORBA.portable.Streamable
{
  public CosEvent.Canal value = null;

  public CanalHolder ()
  {
  }

  public CanalHolder (CosEvent.Canal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosEvent.CanalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosEvent.CanalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosEvent.CanalHelper.type ();
  }

}
