package CosEvent;


/**
* CosEvent/CanalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface CanalOperations 
{
  void add_consumer (CosEvent.ProxyPushConsumer ppc);
  void add_supplier (CosEvent.ProxyPushSupplier pps);
  void remove_consumer (CosEvent.ProxyPushConsumer ppc);
  void remove_supplier (CosEvent.ProxyPushSupplier pps);
  void add_event (CosEvent.Event event);
} // interface CanalOperations
