package CosEvent;

/**
* CosEvent/MessageListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public final class MessageListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public CosEvent.MessageListener value = null;

  public MessageListenerHolder ()
  {
  }

  public MessageListenerHolder (CosEvent.MessageListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosEvent.MessageListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosEvent.MessageListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosEvent.MessageListenerHelper.type ();
  }

}
