package CosEvent;


/**
* CosEvent/MessageListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface MessageListenerOperations 
{
  void receive (CosEvent.Event event);
} // interface MessageListenerOperations
