package CosEvent;


/**
* CosEvent/ProxyPushConsumerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public class ProxyPushConsumerPOATie extends ProxyPushConsumerPOA
{

  // Constructors

  public ProxyPushConsumerPOATie ( CosEvent.ProxyPushConsumerOperations delegate ) {
      this._impl = delegate;
  }
  public ProxyPushConsumerPOATie ( CosEvent.ProxyPushConsumerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CosEvent.ProxyPushConsumerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CosEvent.ProxyPushConsumerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void connect (CosEvent.PushSupplier ps)
  {
    _impl.connect(ps);
  } // connect

  public CosEvent.PushSupplier getSupplier ()
  {
    return _impl.getSupplier();
  } // getSupplier

  public void disconnect ()
  {
    _impl.disconnect();
  } // disconnect

  public void push (CosEvent.Event event)
  {
    _impl.push(event);
  } // push

  private CosEvent.ProxyPushConsumerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ProxyPushConsumerPOATie
