package CosEvent;


/**
* CosEvent/ProxyPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface ProxyPushSupplierOperations  extends CosEvent.PushSupplierOperations
{
  void connect (CosEvent.PushConsumer pc);
  CosEvent.PushConsumer getConsumer ();
} // interface ProxyPushSupplierOperations
