package CosEvent;


/**
* CosEvent/ProxyPushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface ProxyPushConsumer extends ProxyPushConsumerOperations, CosEvent.PushConsumer, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPushConsumer
