package CosEvent;


/**
* CosEvent/ProxyPushConsumerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public abstract class ProxyPushConsumerPOA extends org.omg.PortableServer.Servant
 implements CosEvent.ProxyPushConsumerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
    _methods.put ("getSupplier", new java.lang.Integer (1));
    _methods.put ("disconnect", new java.lang.Integer (2));
    _methods.put ("push", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosEvent/ProxyPushConsumer/connect
       {
         CosEvent.PushSupplier ps = CosEvent.PushSupplierHelper.read (in);
         this.connect (ps);
         out = $rh.createReply();
         break;
       }

       case 1:  // CosEvent/ProxyPushConsumer/getSupplier
       {
         CosEvent.PushSupplier $result = null;
         $result = this.getSupplier ();
         out = $rh.createReply();
         CosEvent.PushSupplierHelper.write (out, $result);
         break;
       }

       case 2:  // CosEvent/PushConsumer/disconnect
       {
         this.disconnect ();
         out = $rh.createReply();
         break;
       }

       case 3:  // CosEvent/PushConsumer/push
       {
         CosEvent.Event event = CosEvent.EventHelper.read (in);
         this.push (event);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosEvent/ProxyPushConsumer:1.0", 
    "IDL:CosEvent/PushConsumer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ProxyPushConsumer _this() 
  {
    return ProxyPushConsumerHelper.narrow(
    super._this_object());
  }

  public ProxyPushConsumer _this(org.omg.CORBA.ORB orb) 
  {
    return ProxyPushConsumerHelper.narrow(
    super._this_object(orb));
  }


} // class ProxyPushConsumerPOA
