package CosEvent;


/**
* CosEvent/PushConsumerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public abstract class PushConsumerPOA extends org.omg.PortableServer.Servant
 implements CosEvent.PushConsumerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("disconnect", new java.lang.Integer (0));
    _methods.put ("push", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosEvent/PushConsumer/disconnect
       {
         this.disconnect ();
         out = $rh.createReply();
         break;
       }

       case 1:  // CosEvent/PushConsumer/push
       {
         CosEvent.Event event = CosEvent.EventHelper.read (in);
         this.push (event);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosEvent/PushConsumer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PushConsumer _this() 
  {
    return PushConsumerHelper.narrow(
    super._this_object());
  }

  public PushConsumer _this(org.omg.CORBA.ORB orb) 
  {
    return PushConsumerHelper.narrow(
    super._this_object(orb));
  }


} // class PushConsumerPOA
