package CosEvent;


/**
* CosEvent/PushSupplierPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public class PushSupplierPOATie extends PushSupplierPOA
{

  // Constructors

  public PushSupplierPOATie ( CosEvent.PushSupplierOperations delegate ) {
      this._impl = delegate;
  }
  public PushSupplierPOATie ( CosEvent.PushSupplierOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CosEvent.PushSupplierOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CosEvent.PushSupplierOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void disconnect ()
  {
    _impl.disconnect();
  } // disconnect

  public void receive (CosEvent.Event event)
  {
    _impl.receive(event);
  } // receive

  private CosEvent.PushSupplierOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class PushSupplierPOATie
