module cosevent {
	
	struct Event{
		long timeStamp;
		any content;
	};
	
	exception AlreadyRegisteredException{
		string message;
	};
	
	exception NotRegisteredException{
		string message;
	};
	
	exception AlreadyConnectedException{
		string message;
	};
	
	exception NotConnectedException{
		string message;
	};
	
	exception MaximalConnectionReachedException{
		string message;
	};
	
	exception ChannelNotFoundException{
		string message;
	};
	
	exception ConsumerNotFoundException{
		string message;
	};
	
	interface Consumer{
	};
	
	interface Supplier{
	};
	
	interface CallbackConsumer{
		void receive(in Event evt) raises (ConsumerNotFoundException);
	};
		
	interface ProxyForPushConsumer : Consumer{
			
		void subscribe(in CallbackConsumer cc) raises (ChannelNotFoundException,AlreadyRegisteredException);
		void unsubscribe() raises (ChannelNotFoundException,NotRegisteredException);
		void connect() raises (ChannelNotFoundException,AlreadyConnectedException,MaximalConnectionReachedException,NotRegisteredException);
		void disconnect() raises (ChannelNotFoundException,NotConnectedException,NotRegisteredException);
		
	};
	
	interface ProxyForPushSupplier : Supplier{
		void connect() raises (ChannelNotFoundException,AlreadyConnectedException,MaximalConnectionReachedException);
		void push(in Event evt) raises (ChannelNotFoundException);
		void disconnect() raises (ChannelNotFoundException,NotConnectedException);
	};
	
	interface ChannelAdmin{
		ProxyForPushConsumer getProxyForPushConsumer(in string topic) raises (ChannelNotFoundException);
		ProxyForPushSupplier getProxyForPushSupplier(in string topic) raises (ChannelNotFoundException);
	};
};
