module monitoring {
  
	struct PushConsumerStat{
   	 string id;
   	 boolean connected;
   	 long nbQueueEvents;					//Nombre evenemnt dans la queue
   	 long nbReceivedEvents;					//Nombre Evenement envoyé
    };
    
    struct PushSupplierStat{
   	 string id;								//Qui a envoyé?
   	 long pushedEvents;						//Nombre Events Envoyé
    };
    
    struct ChannelInfoscollector{
   	 string topic;							//Titre
   	 long capacity;							//Capacité
   	 long nbQueueEvents;					//nombre Events in the queue
   	 sequence<PushConsumerStat> consumers;	//Connecté et abonnée
   	 sequence<PushSupplierStat> suppliers;	//Connecté
    };
   
   typedef sequence<ChannelInfoscollector> ChannelsInfos;   
   
    interface CosInfoCollector{
   	 	ChannelsInfos getChannelsInfos();   	 	
    };
};
