
module costime{
	typedef unsigned long long DateTime;
	exception AlreadyRegisteredException{
		string message;
	};
	exception NotRegisteredException{
		string message;
	};
	exception UnreachableException{
		string message;
	};
	interface Synchronizable{
		 attribute DateTime date;
	};
	interface TimeService{
		void subscribe(in Synchronizable cc) raises (AlreadyRegisteredException);
		void unsubscribe(in Synchronizable cc) raises (NotRegisteredException);
	};
};

