module costime{
	typedef unsigned long DateTime;
	exception AlreadyRegisteredException{
		string message;
	};
	exception NotRegisteredException{
		string message;
	};
	exception UnreachableException{
		string message;
	};
	interface Synchronizable{
		 attribute DateTime date;
	};
	interface TimeService{
		void subscribe(in Synchronizable cc) raises (AlreadyRegisteredException,UnreachableException);
		void unsubscribe() raises (UnreachableException,NotRegisteredException);
	};
};

