module costime{
	typedef unsigned long DateTime;
	exception AlreadyRegisteredException{
		string message;
	};
	exception NotRegisteredException{
		string message;
	};
	exception UnreachableException{
		string message;
	};
	interface Synchronizable{
		attribute DateTime date;
		void setDate(in DateTime date);
	};
	interface TimeService{
		void subscribe(in Synchronizable cc) raises (ChannelNotFoundException,AlreadyRegisteredException);
		void unsubscribe() raises (ChannelNotFoundException,NotRegisteredException);
	};
};

