package com.esiag.client;

/**
* InterfaceIDL/ImprimanteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Imprimante.idl
* mercredi 6 octobre 2010 13 h 35 CEST
*/

public final class ImprimanteHolder implements org.omg.CORBA.portable.Streamable
{
  public Imprimante value = null;

  public ImprimanteHolder ()
  {
  }

  public ImprimanteHolder (Imprimante initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ImprimanteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ImprimanteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ImprimanteHelper.type ();
  }

}
