package InterfaceIDL;


/**
* InterfaceIDL/TacheRefusee.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Imprimante.idl
* mercredi 6 octobre 2010 13 h 35 CEST
*/

public final class TacheRefusee extends org.omg.CORBA.UserException
{
  public String imprimante = null;
  public String raison = null;

  public TacheRefusee ()
  {
    super(TacheRefuseeHelper.id());
  } // ctor

  public TacheRefusee (String _imprimante, String _raison)
  {
    super(TacheRefuseeHelper.id());
    imprimante = _imprimante;
    raison = _raison;
  } // ctor


  public TacheRefusee (String $reason, String _imprimante, String _raison)
  {
    super(TacheRefuseeHelper.id() + "  " + $reason);
    imprimante = _imprimante;
    raison = _raison;
  } // ctor

} // class TacheRefusee
