package CosEvent;

/**
* CosEvent/EventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public final class EventHolder implements org.omg.CORBA.portable.Streamable
{
  public CosEvent.Event value = null;

  public EventHolder ()
  {
  }

  public EventHolder (CosEvent.Event initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosEvent.EventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosEvent.EventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosEvent.EventHelper.type ();
  }

}
