package CosEvent;


/**
* CosEvent/EventChannelPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public class EventChannelPOATie extends EventChannelPOA
{

  // Constructors

  public EventChannelPOATie ( CosEvent.EventChannelOperations delegate ) {
      this._impl = delegate;
  }
  public EventChannelPOATie ( CosEvent.EventChannelOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CosEvent.EventChannelOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CosEvent.EventChannelOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public CosEvent.ProxyPushSupplier get_Proxy_Push_Supplier ()
  {
    return _impl.get_Proxy_Push_Supplier();
  } // get_Proxy_Push_Supplier

  public CosEvent.ProxyPushConsumer get_Proxy_Push_Consumer ()
  {
    return _impl.get_Proxy_Push_Consumer();
  } // get_Proxy_Push_Consumer

  private CosEvent.EventChannelOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class EventChannelPOATie
