package CosEvent;

/**
* CosEvent/EventChannelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public final class EventChannelHolder implements org.omg.CORBA.portable.Streamable
{
  public CosEvent.EventChannel value = null;

  public EventChannelHolder ()
  {
  }

  public EventChannelHolder (CosEvent.EventChannel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosEvent.EventChannelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosEvent.EventChannelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosEvent.EventChannelHelper.type ();
  }

}
