package CosEvent;


/**
* CosEvent/EventPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public class EventPOATie extends EventPOA
{

  // Constructors

  public EventPOATie ( CosEvent.EventOperations delegate ) {
      this._impl = delegate;
  }
  public EventPOATie ( CosEvent.EventOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CosEvent.EventOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CosEvent.EventOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String event ()
  {
    return _impl.event();
  } // event
  public void event (String newEvent)
  {
    _impl.event(newEvent);
  } // event

  private CosEvent.EventOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class EventPOATie
