package CosEvent;


/**
* CosEvent/EventChannelPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public abstract class EventChannelPOA extends org.omg.PortableServer.Servant
 implements CosEvent.EventChannelOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get_Proxy_Push_Supplier", new java.lang.Integer (0));
    _methods.put ("get_Proxy_Push_Consumer", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosEvent/EventChannel/get_Proxy_Push_Supplier
       {
         CosEvent.ProxyPushSupplier $result = null;
         $result = this.get_Proxy_Push_Supplier ();
         out = $rh.createReply();
         CosEvent.ProxyPushSupplierHelper.write (out, $result);
         break;
       }

       case 1:  // CosEvent/EventChannel/get_Proxy_Push_Consumer
       {
         CosEvent.ProxyPushConsumer $result = null;
         $result = this.get_Proxy_Push_Consumer ();
         out = $rh.createReply();
         CosEvent.ProxyPushConsumerHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosEvent/EventChannel:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EventChannel _this() 
  {
    return EventChannelHelper.narrow(
    super._this_object());
  }

  public EventChannel _this(org.omg.CORBA.ORB orb) 
  {
    return EventChannelHelper.narrow(
    super._this_object(orb));
  }


} // class EventChannelPOA
