package CosEvent;


/**
* CosEvent/EventPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public abstract class EventPOA extends org.omg.PortableServer.Servant
 implements CosEvent.EventOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_event", new java.lang.Integer (0));
    _methods.put ("_set_event", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosEvent/Event/_get_event
       {
         String $result = null;
         $result = this.event ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CosEvent/Event/_set_event
       {
         String newEvent = in.read_string ();
         this.event (newEvent);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosEvent/Event:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Event _this() 
  {
    return EventHelper.narrow(
    super._this_object());
  }

  public Event _this(org.omg.CORBA.ORB orb) 
  {
    return EventHelper.narrow(
    super._this_object(orb));
  }


} // class EventPOA
