package CosEvent;


/**
* CosEvent/EventChannelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface EventChannelOperations 
{
  CosEvent.ProxyPushSupplier get_Proxy_Push_Supplier ();
  CosEvent.ProxyPushConsumer get_Proxy_Push_Consumer ();
} // interface EventChannelOperations
