package CosEvent;


/**
* CosEvent/MessageListenerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public class MessageListenerPOATie extends MessageListenerPOA
{

  // Constructors

  public MessageListenerPOATie ( CosEvent.MessageListenerOperations delegate ) {
      this._impl = delegate;
  }
  public MessageListenerPOATie ( CosEvent.MessageListenerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CosEvent.MessageListenerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CosEvent.MessageListenerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void receive (CosEvent.Event event)
  {
    _impl.receive(event);
  } // receive

  private CosEvent.MessageListenerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MessageListenerPOATie
