package CosEvent;


/**
* CosEvent/ProxyPushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface ProxyPushConsumerOperations  extends CosEvent.PushConsumerOperations
{
  void connect (CosEvent.PushSupplier ps);
  CosEvent.PushSupplier getSupplier ();
} // interface ProxyPushConsumerOperations
