package CosEvent;


/**
* CosEvent/PushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prototype.idl
* samedi 27 novembre 2010 15 h 07 CET
*/

public interface PushSupplier extends PushSupplierOperations, CosEvent.MessageListener, org.omg.CORBA.portable.IDLEntity 
{
} // interface PushSupplier
